print("  ____    _    ____  _   _ ____  ")
print(" / ___|  / \  |  _ \| | | |  _ \ ")
print(" \___ \ / _ \ | |_) | | | | |_) |")
print("  ___) / ___ \|  __/| |_| |  _ <")
print("|____/_/   \_\_|    \___/|_| \_\ ")
print("  ____   _____  __              ")
print(" |  _ \ / _ \ \/ /               ")
print(" | | | | | | \  /                ")
print(" | |_| | |_| /  \                ")
print(" |____/ \___/_/\_\               ")
print("                                 ")
un = input("Please enter the username of the person you would like to search for")
print("https://twitter.com/" + un)
print("https://youtube.com/results?search_query="+ un)
print("https://twitter.com/" + un)
print("https://reddit.com/user/" + un)
print("https://namemc.com/profile/" + un)
print("https://twitch.tv/" + un)
print("https://github.com/" + un)
print("https://www.instagram.com/" + un)
print("https://www.facebook.com/" + un)
print("https://www.flickr.com/search/?text=" + un)
print("https://www.chess.com/member/" + un)
print("scratch.mit.edu/users/" + un)
print("https://lichess.org/@/" + un)
print("https://osu.ppy.sh/users/" + un)
print("https://xboxgamertag.com/search/" + un)
print("tiktok.com/" + un)
print("pornhub.com/" + un)
print("𝒮𝒶𝓅𝓊𝓇𝒟𝑜𝓍 𝒱𝑒𝓇𝓈𝒾𝑜𝓃: 𝒷𝑒𝓉𝒶 𝟣.2")
print("Need help? Dm Sapur1#2930 on discord!")
